### ISSUE TITLE
error loadDefinitions()

### ISSUE THREAD

**Issue by landsman** [adeira/monolog#1]
Hi,

after I was download extension nette says:
Call to undefined static method Nette\DI\Compiler::loadDefinitions()

extensions:
    monolog: Adeira\Monolog\DI\MonologExtension

nette v2.3

**Comment by mrtnzlml** [comment]
Probably bad packages version. Can you send me output of `composer show` please? (`composer show --installed` with older Composer). It should print only installed currently packages...
