### ISSUE TITLE
Contributte

### ISSUE THREAD

**Issue by f3l1x** [adeira/monolog#2]
Hi!

According to this tweet: https://twitter.com/mrtnzlml/status/886504837856337921

I would like to move this package under contributte namespace and try to maintain it. Do you agree? :-)

One little thing bait me, it depends on kdyby/monolog. I would like to separate it. Do you agree?

**Comment by mrtnzlml** [comment]
Absolutamente. You have my approval. What should I do to make this happen?

**Comment by f3l1x** [comment]
Please arrange the transfer under contributte organization ;-)

**Comment by mrtnzlml** [comment]
What will happen with the current Composer installations via `adeira/monolog`? Will it still work?

**Comment by f3l1x** [comment]
Yes, composer depends on configuration in composer.json. In the future, we should change it to contributte and deprecate the adeira/monolog. Right?

**Comment by f3l1x** [comment]
Thanks. It'll be in good hands. ✋
